import {handleSitesApi as handleApi} from "../../worker/sites-api";
import {beforeEach,afterEach,it,expect} from "vitest";
import {readFileSync} from "node:fs";
import {SqliteTestDatabase} from "./sqlite-test-db";
import {type Env} from "../../worker/api";
import {acceptableJpeg} from "../../worker/home-photos";
let db:SqliteTestDatabase,env:Env;const objects=new Map<string,Uint8Array>();
const base="https://myintel.test",requestId="request-home",id="00000000-0000-4000-8000-000000000001";
const jpeg=new Uint8Array([255,216,255,224,0,2,255,192,0,8,8,0,1,0,1,0,255,218,0,2,255,217]);
function call(path:string,method="GET",user="owner",data?:Uint8Array){return handleApi(new Request(base+path,{method,headers:{origin:base,"oai-authenticated-user-id":user,"oai-authenticated-user-email":user+"@example.test","Content-Type":"image/jpeg","X-Photo-Room":"Living%20room","X-Photo-Kind":"wide","X-Photo-Consent":"yes"},body:data?Uint8Array.from(data).buffer:undefined}),env)}
beforeEach(()=>{db=new SqliteTestDatabase();db.sqlite.exec(readFileSync(new URL("../../drizzle/0001_nebulous_karma.sql",import.meta.url),"utf8"));objects.clear();env={DB:db,ASSETS:{fetch:async()=>new Response()},MYINTEL_ADMIN_EMAIL:"admin@example.test",BUCKET:{put:async(k,b)=>{objects.set(k,b)},get:async k=>objects.has(k)?{body:new Response(Uint8Array.from(objects.get(k)!).buffer).body!}:null,delete:async k=>{objects.delete(k)}}};db.sqlite.exec("INSERT INTO service_requests (id,user_id,email,service,name,postal_code,contact_method,relationship,consent_at,created_at,updated_at) VALUES ('request-home','owner','owner@example.test','professional_assessment','Example','00000','email','self','now','now','now')");db.sqlite.prepare("INSERT INTO home_handoffs VALUES (?,?,?)").run(requestId,JSON.stringify({summary:"Example shared report",rooms:["Living room"],savedAt:"now"}),"now")});
afterEach(()=>db.close());
it("checks ownership before revealing shared reports or images",async()=>{expect((await call(`/api/requests/${requestId}/home-review`,"GET","other")).status).toBe(404);expect((await call(`/api/requests/${requestId}/home-review/photos/${id}`,"PUT","other",jpeg)).status).toBe(404);expect(objects.size).toBe(0)});
it("uploads once, allows owner and staff viewing, and supports owner removal",async()=>{const path=`/api/requests/${requestId}/home-review/photos/${id}`;expect((await call(path,"PUT","owner",jpeg)).status).toBe(201);expect((await call(path,"PUT","owner",jpeg)).status).toBe(200);expect(objects.size).toBe(1);expect((await call(path,"GET","admin")).headers.get("Content-Type")).toBe("image/jpeg");expect((await call(path,"DELETE","admin")).status).toBe(403);expect((await call(path,"DELETE","owner")).status).toBe(200);expect(objects.size).toBe(0);expect((await call(path)).status).toBe(404)});
it("refuses unsupported content, original EXIF and uploads without shared context",async()=>{expect(acceptableJpeg(new Uint8Array([255,216,255,225,0,2,255,218,0,2]))).toBe(false);expect((await call(`/api/requests/${requestId}/home-review/photos/${id}`,"PUT","owner",new TextEncoder().encode("<svg/>"))).status).toBe(400);db.sqlite.exec("DELETE FROM home_handoffs");expect((await call(`/api/requests/${requestId}/home-review/photos/${id}`,"PUT","owner",jpeg)).status).toBe(409)});
it("enforces a six-photo limit on the server",async()=>{for(let n=0;n<6;n++)db.sqlite.prepare("INSERT INTO home_photos VALUES (?,?,?,?,?,1,?)").run("existing-"+n,requestId,"Living room","wide","key"+n,"now");expect((await call(`/api/requests/${requestId}/home-review/photos/${id}`,"PUT","owner",jpeg)).status).toBe(409);expect(objects.size).toBe(0)});
it("fails honestly when object storage is unavailable",async()=>{delete env.BUCKET;expect((await call(`/api/requests/${requestId}/home-review/photos/${id}`,"PUT","owner",jpeg)).status).toBe(503)});
it("shares a saved family snapshot only with explicit permission and correct ownership",async()=>{
 const archive={cases:[{id:"family",audience:"family",spaces:[{id:"living",type:"living",label:"Living room"}],familyAnswers:{}}]};
 db.sqlite.prepare("INSERT INTO case_archives VALUES (?,?,1,'now')").run("owner",JSON.stringify(archive));
 const send=(shareAssessment:boolean,caseId="family")=>handleApi(new Request(base+"/api/requests",{method:"POST",headers:{origin:base,"Content-Type":"application/json","oai-authenticated-user-id":"owner","oai-authenticated-user-email":"owner@example.test"},body:JSON.stringify({idempotencyKey:crypto.randomUUID(),service:"professional_assessment",name:"Example User",postalCode:"00000",contactMethod:"email",relationship:"self",consent:true,shareAssessment,caseId})}),env);
 expect((await send(true,"not-owned")).status).toBe(400);
 const alone=await send(false);expect(alone.status).toBe(201);const aloneId=(await alone.json()).request.id;expect(db.sqlite.prepare("SELECT * FROM home_handoffs WHERE request_id=?").get(aloneId)).toBeUndefined();
 const shared=await send(true);expect(shared.status).toBe(201);const sharedId=(await shared.json()).request.id;
 const snapshot=db.sqlite.prepare("SELECT payload FROM home_handoffs WHERE request_id=?").get(sharedId)!.payload as string;expect(JSON.parse(snapshot).rooms).toEqual(["Living room"]);
 db.sqlite.prepare("UPDATE case_archives SET payload=? WHERE user_id='owner'").run(JSON.stringify({cases:[]}));expect(db.sqlite.prepare("SELECT payload FROM home_handoffs WHERE request_id=?").get(sharedId)!.payload).toBe(snapshot);
});
