import {describe,it,expect} from "vitest";
import {EMPTY_PROFILE,profileSchema,familyTemplateFor,selectContextRooms,profileLines,type HomeProfile} from "@/domain/home-profile";
import {emptyDynamicContext,contextPrompts,answerContext,leaveContextUnknown,taskPlace,activeContextAnswers,contextGaps} from "@/domain/dynamic-context";
import {familyItemsFor} from "@/domain/family";
import {buildFamilyReport} from "@/domain/family-report";
import {homeActions} from "@/domain/home-actions";
import {normalise,readArchive} from "@/lib/case-store";
const profile=():HomeProfile=>({...EMPTY_PROFILE,dynamic:emptyDynamicContext()});
const answer=(p:HomeProfile,id:string,value:string|string[]):HomeProfile=>({...p,...answerContext(p,id,value)});
const ids=(p:HomeProfile)=>contextPrompts(p).map(q=>q.id);
describe("purposeful question routing",()=>{
 it("does not promote historical default room counts to confirmed layout",()=>{const p=profile();expect(p.bedrooms).toBe(1);expect(p.dynamic!.layout.bedrooms).toBeNull();expect(profileLines(p).join(" ")).toContain("not provided");expect(contextGaps(p)).toContain("Home layout summary has not been confirmed.");expect(profileSchema.parse(EMPTY_PROFILE)).toEqual(EMPTY_PROFILE)});
 it("reuses the known bathing place and asks task-specific details and support",()=>{let p=profile();p.dynamic!.places=[{id:"bath",type:"bathroom",label:"Upstairs shower",level:2}];p.dynamic!.layout.bathingId="bath";p=answer(p,"personal",["bathing"]);p=answer(p,"task:bathing","help");expect(ids(p)).toContain("part:bathing");expect(ids(p)).toContain("support:bathing");expect(ids(p)).not.toContain("location:bathing");expect(contextPrompts(p).find(q=>q.id==="task:bathing")?.why).toContain("Upstairs shower")});
 it("drops redundant food-access questions when cooking was already selected",()=>{const p=answer(profile(),"household",["cooking"]);expect(ids(p)).not.toContain("foodAccess");expect(ids(p)).toContain("task:cooking");expect(p.foodAccess).toBeUndefined()});
 it("keeps appetite concerns accessible independently of regular meals",()=>{let p=answer(profile(),"meals","regular");p=answer(p,"eatingChanges","yes");expect(ids(p)).toContain("appetite");expect(p.meals).toBe("regular")});
 it("does not infer loneliness or a support gap from living alone",()=>{let p:HomeProfile={...profile(),livingWith:"alone" as const};p=answer(p,"social","enough");expect(ids(p)).not.toContain("socialBarriers");expect(ids(p)).toContain("helpReach");expect(p.helpReach).toBeUndefined()});
 it("retains hidden answers in history without using them for current conclusions",()=>{let p=answer(profile(),"personal",["eating"]);p=answer(p,"task:eating","help");p=answer(p,"part:eating","swallowing");p=answer(p,"personal",["none"]);expect(p.dynamic!.answers["part:eating"]).toBe("swallowing");expect(activeContextAnswers(p)["part:eating"]).toBeUndefined();expect(ids(p)).not.toContain("task:eating");const report=buildFamilyReport([],{});expect(homeActions(report,p).some(a=>a.id==="activity-eating")).toBe(false);expect(p.dynamic!.history).toHaveLength(4)});
 it("rejects impossible answer combinations and inapplicable follow-ups",()=>{expect(()=>answer(profile(),"personal",["none","bathing"])).toThrow();expect(()=>answer(profile(),"part:bathing","standing")).toThrow();expect(()=>answer(profile(),"personal",["invented"])).toThrow()});
 it("filters stale movement detail when daily demands change",()=>{let p=answer(profile(),"demands",["stairs"]);p=answer(p,"movement","difficult");p=answer(p,"demandDifficulty",["stairs"]);p=answer(p,"demands",["outside"]);expect(activeContextAnswers(p).demandDifficulty).toBeUndefined();expect(p.dynamic!.answers.demandDifficulty).toEqual(["stairs"])});
 it("preserves room identity and answers across exclusion and restoration",()=>{const bath={id:"bath1",type:"bathroom" as const,label:"Main bath",level:2};const second={...bath,id:"bath2",label:"Other bath"};const first=selectContextRooms([bath,second],[second]);expect(first.find(s=>s.id==="bath1")?.excludedFromHome).toBe(true);const restored=selectContextRooms(first,[bath,second]);expect(restored.filter(s=>!s.excludedFromHome).map(s=>s.id)).toEqual(["bath1","bath2"])});
 it("removes only established irrelevant entry checks and keeps earlier answered details in reports",()=>{const p=profile(),s={id:"entry",type:"entry" as const,label:"Entrance"};p.dynamic!.places=[{...s,level:null}];p.dynamic!.layout.confirmed=true;p.dynamic!.layout.entranceSteps="none";const t=familyTemplateFor(s,p);expect(familyItemsFor(t).map(i=>i.code)).not.toContain("e5");const report=buildFamilyReport([{...s,template:t}],{"entry::e5":"no"});expect(report.priority.some(e=>e.code==="e5")).toBe(true);p.dynamic!.layout.confirmed=false;expect(familyItemsFor(familyTemplateFor(s,p)).map(i=>i.code)).toContain("e5")});
 it("opens purposeful environmental detail but never creates clinical ratings",()=>{const p=profile(),s={id:"bath",type:"bathroom" as const,label:"Bath"};const t=familyTemplateFor(s,p,{"bath::b2":"unsure"});expect(familyItemsFor(t).map(i=>i.code)).toContain("b4");const state=normalise({id:"home",audience:"family",homeProfile:p,familyAnswers:{"bath::b2":"unsure"}});expect(state.responses).toEqual({});const saved=readArchive(JSON.stringify({activeId:state.id,cases:[state]}));expect(saved.cases[0]?.homeProfile).toEqual(p)});
});

it("does not recommend help from an appetite answer hidden by a corrected response",()=>{let p=answer(profile(),"eatingChanges","yes");p=answer(p,"appetite","swallowing");p=answer(p,"eatingChanges","none");expect(p.appetite).toBe("swallowing");expect(homeActions(buildFamilyReport([],{}),p).some(a=>a.step.includes("choking"))).toBe(false);expect(profileLines(p).join(" ")).not.toContain("Difficulty swallowing")});
it("clears an explicitly skipped answer without deleting its earlier history",()=>{let p=answer(profile(),"movement","difficult");p={...p,...leaveContextUnknown(p,"movement")};expect(p.movement).toBeUndefined();expect(ids(p)).not.toContain("demandDifficulty");expect(p.dynamic!.history[0]?.value).toBe("difficult");expect(contextGaps(p).join(" ")).toContain("How is getting around")});
it("uses a revised usual bathing place instead of a stale location answer",()=>{const p=profile();p.dynamic!.places=[{id:"old",type:"bathroom",label:"Old",level:1},{id:"new",type:"bathroom",label:"New",level:2}];p.dynamic!.answers["location:bathing"]="old";p.dynamic!.layout.bathingId="new";expect(taskPlace(p,"bathing")?.id).toBe("new")});

it("exposes inconsistent reported room counts and levels without guessing corrections",()=>{const p=profile();p.dynamic!.layout.bedrooms=0;p.dynamic!.layout.levels=1;p.dynamic!.places=[{id:"bed",type:"bedroom",label:"Bedroom",level:2}];expect(contextGaps(p).join(" ")).toContain("exceed the reported home inventory");expect(contextGaps(p).join(" ")).toContain("outside the reported home layout");expect(p.dynamic!.layout.bedrooms).toBe(0)});
