import {describe,it,expect} from "vitest";
import {EMPTY_PROFILE,suggestedRooms,selectUsedRooms,activeHomeSpaces,familyTemplateFor,profileSchema} from "@/domain/home-profile";
import {buildFamilyReport} from "@/domain/family-report";
import {homeActions,homeActionsText} from "@/domain/home-actions";
describe("everyday home check",()=>{
 it("uses occupied spaces instead of total bedroom counts or levels",()=>{const spaces=suggestedRooms({...EMPTY_PROFILE,bedrooms:8,fullBaths:6,levels:4,stairs:"yes",usedAreas:["bedroom","bathroom"]});expect(spaces).toHaveLength(2);expect(spaces.map(s=>s.type)).toEqual(["bedroom","bathroom"]);const report=buildFamilyReport(spaces.map(s=>({...s,template:familyTemplateFor(s)})),{});expect(report.totalCount).toBe(15)});
 it("does not silently add a default area when nothing is selected",()=>{expect(suggestedRooms({...EMPTY_PROFILE,usedAreas:[]})).toEqual([])});
 it("sets aside unused rooms and restores their IDs and saved answers",()=>{const existing=[{id:"bed",type:"bedroom" as const,label:"Bedroom"},{id:"spare",type:"bedroom" as const,label:"Spare bedroom"}];const selected=selectUsedRooms(existing,suggestedRooms({...EMPTY_PROFILE,usedAreas:["bedroom"]}));expect(activeHomeSpaces(selected).map(s=>s.id)).toEqual(["bed"]);expect(selected.find(s=>s.id==="spare")?.excludedFromHome).toBe(true);const restored=selected.map(s=>({...s,excludedFromHome:false}));expect(activeHomeSpaces(restored).map(s=>s.id)).toEqual(["bed","spare"]);expect(selectUsedRooms(selected,suggestedRooms({...EMPTY_PROFILE,usedAreas:["bedroom"]}))).toEqual(selected)});
 it("keeps set-aside answers out of coverage and findings",()=>{const spaces=[{id:"used",type:"bathroom" as const,label:"Bathroom"},{id:"unused",type:"bathroom" as const,label:"Spare",excludedFromHome:true}];const report=buildFamilyReport(activeHomeSpaces(spaces).map(s=>({...s,template:familyTemplateFor(s)})),{"unused::b1":"no"});expect(report.flaggedCount).toBe(0);expect(report.answeredCount).toBe(0);expect(report.rooms).toHaveLength(1)});
 it("does not turn uncertainty into a DIY or modification recommendation",()=>{const report=buildFamilyReport([{id:"bath",label:"Bath",template:familyTemplateFor({type:"bathroom"})}],{"bath::b1":"unsure"});expect(homeActions(report).map(a=>a.id)).toEqual(["clarify"])});
 it("respects technology opt-out while still addressing a gap in reaching help",()=>{const report=buildFamilyReport([],{});const profile={...EMPTY_PROFILE,helpReach:"no" as const,technology:"no" as const};expect(homeActions(report,profile).map(a=>a.id)).toEqual(["help"]);expect(homeActionsText(report,profile)).toContain("Agree how help would be reached")});
 it("persists used areas and support preferences without changing old profiles",()=>{expect(profileSchema.parse(EMPTY_PROFILE)).toEqual(EMPTY_PROFILE);expect(profileSchema.parse({...EMPTY_PROFILE,usedAreas:["half_bath"],technology:"help"}).usedAreas).toEqual(["half_bath"])});
});
