// @vitest-environment jsdom
import {afterEach,beforeEach,expect,it,vi} from "vitest";
import {act,createElement} from "react";
import {createRoot,type Root} from "react-dom/client";
import {HomeSectionPause} from "@/components/HomeSectionPause";
import {HomeRoutineConversation} from "@/components/HomeRoutineConversation";
import {useCase} from "@/lib/case-store";
let root:Root,container:HTMLDivElement;
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});vi.spyOn(window,"scrollTo").mockImplementation(()=>{});localStorage.clear();container=document.createElement("div");document.body.append(container);root=createRoot(container)});
afterEach(()=>{act(()=>root.unmount());container.remove();vi.restoreAllMocks()});
async function click(text:string){const button=[...container.querySelectorAll("button")].find(b=>b.textContent===text);if(!button)throw Error(text);await act(async()=>button.click())}
it("keeps questions absent until the reader continues, then moves focus",async()=>{await act(async()=>root.render(createElement(HomeSectionPause,{title:"Next room",detail:"Take your time",children:createElement("h1",{tabIndex:-1},"Room question")})));expect(container.textContent).not.toContain("Room question");expect(document.activeElement?.textContent).toBe("Next room");await click("Continue");expect(container.textContent).toContain("Room question");expect(document.activeElement?.textContent).toBe("Room question")});
it("keeps the goal and identity choices when going back",async()=>{function Harness(){const api=useCase();return createElement(HomeRoutineConversation,{api})}await act(async()=>root.render(createElement(Harness)));const self=[...container.querySelectorAll("button")].find(b=>b.textContent?.includes("Myself"))!;await act(async()=>self.click());await click("Continue");expect(container.textContent).toContain("What matters most right now?");await click("Back");expect([...container.querySelectorAll("button")].find(b=>b.textContent?.includes("Myself"))?.getAttribute("aria-pressed")).toBe("true")});
it("inserts and removes a movement follow-up without losing the stored answer",async()=>{let api!:ReturnType<typeof useCase>;function Harness(){api=useCase();return createElement(HomeRoutineConversation,{api})}await act(async()=>root.render(createElement(Harness)));await act(async()=>api.setFamilyPosition({phase:"routine",roomIndex:0,contextQuestionId:"movement"}));const choose=async(text:string)=>{const b=[...container.querySelectorAll("button")].find(b=>b.textContent?.includes(text))!;await act(async()=>b.click())};await choose("Difficult or tiring");await click("Continue");expect(container.textContent).toContain("Which movement needs the most support?");await choose("Steps or stairs");await click("Back");await choose("Usually comfortable");await click("Continue");expect(container.textContent).toContain("What helps with getting around?");expect(api.state.homeProfile?.dynamic?.answers.demandDifficulty).toEqual(["stairs"])});
it("persists the current context question when interrupted",async()=>{let api!:ReturnType<typeof useCase>;function Harness(){api=useCase();return createElement(HomeRoutineConversation,{api})}await act(async()=>root.render(createElement(Harness)));await act(async()=>api.setFamilyPosition({phase:"routine",roomIndex:0,contextQuestionId:"social"}));expect(container.textContent).toContain("as much contact");await act(async()=>api.setFamilyPosition({phase:"routine",roomIndex:0,contextQuestionId:"review"}));expect(container.textContent).toContain("A check built around");await click("Review everyday life");expect(container.textContent).toContain("Which personal activities");});
