import {describe,it,expect} from "vitest";
import {EMPTY_PROFILE,suggestedRooms,mergeSuggestedRooms,familyTemplateFor,profileSchema} from "@/domain/home-profile";
import {familyProgress} from "@/domain/family";
import {buildFamilyReport} from "@/domain/family-report";
import {savedCaseSchema} from "@/lib/case-validation";
describe("personalized home checklist",()=>{
 it("prepares a 3 bed, 2.5 bath, 2 level townhome with a separate half bath",()=>{const rooms=suggestedRooms({...EMPTY_PROFILE,homeType:"townhome",bedrooms:3,fullBaths:2,halfBaths:1,levels:2,stairs:"yes"});expect(rooms.filter(r=>r.type==="bedroom")).toHaveLength(3);expect(rooms.filter(r=>r.type==="bathroom")).toHaveLength(3);expect(rooms.filter(r=>r.familyKind==="half_bath")).toHaveLength(1);expect(rooms.filter(r=>r.type==="stairway")).toHaveLength(1);expect(rooms).toHaveLength(10)});
 it("leaves shower questions out of a half bath across questions, coverage and report",()=>{const room={id:"half",type:"bathroom" as const,label:"Half bath",familyKind:"half_bath" as const};const template=familyTemplateFor(room);expect(template.items.some(i=>["b2","b3","b4","b8"].includes(i.code))).toBe(false);const answers={"half::b2":"yes" as const};const progress=familyProgress([{spaceId:room.id,template}],answers);const report=buildFamilyReport([{...room,template}],answers);expect(progress.answered).toBe(0);expect(report.answeredCount).toBe(0);expect(report.totalCount).toBe(progress.total);expect(familyTemplateFor({...room,familyKind:undefined}).items.some(i=>i.code==="b2")).toBe(true)});
 it("uses routines for order without fabricating answers or ratings",()=>{const normal=suggestedRooms({...EMPTY_PROFILE,stairs:"no"});const night=suggestedRooms({...EMPTY_PROFILE,stairs:"no",routines:["night"]});expect(night[0]?.type).toBe("bedroom");expect(normal.map(r=>r.id).sort()).toEqual(night.map(r=>r.id).sort());expect(night.every(r=>!r.level)).toBe(true)});
 it("preserves existing IDs, room labels, levels and extra rooms when setup is edited",()=>{const existing=[{id:"old",type:"bedroom" as const,label:"My bedroom",level:2},{id:"extra",type:"exterior" as const,label:"Deck"}];const first=mergeSuggestedRooms(existing,suggestedRooms(EMPTY_PROFILE));expect(first.find(r=>r.id==="old")).toEqual(existing[0]);expect(first.some(r=>r.id==="extra")).toBe(true);expect(mergeSuggestedRooms(first,suggestedRooms(EMPTY_PROFILE))).toEqual(first)});
 it("does not invent stairs in an explicitly stair-free multi-level home",()=>{expect(suggestedRooms({...EMPTY_PROFILE,levels:2,stairs:"no"}).some(r=>r.type==="stairway")).toBe(false)});
 it("rejects impossible counts and round-trips saved profile and half-bath metadata",()=>{expect(profileSchema.safeParse({...EMPTY_PROFILE,bedrooms:99}).success).toBe(false);const sample={homeProfile:EMPTY_PROFILE,spaces:[{id:"half",type:"bathroom",label:"Half",familyKind:"half_bath",level:2}],familyPosition:{phase:"home",roomIndex:0}};expect(savedCaseSchema.parse(sample)).toEqual(sample)});
});
