// @vitest-environment jsdom
import {act,createElement} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {PlanCapture} from '../../src/components/PlanCapture';
import ProfessionalHelp from '../../src/components/ProfessionalHelp';
import {EMPTY_CASE,normalise} from '../../src/lib/case-store';
const user={id:'alice',name:'Example',email:'alice@example.test',isAdmin:false};
const home=normalise({...EMPTY_CASE,id:'current',audience:'family',spaces:[{id:'bath',type:'bathroom',label:'Example bathroom'}],familyPosition:{phase:'report',roomIndex:0}});
let root:Root,container:HTMLDivElement,fetchMock:ReturnType<typeof vi.fn>;
const button=(text:string)=>[...container.querySelectorAll('button')].find(e=>e.textContent?.includes(text))!;
async function fill(label:string,value:string){await act(async()=>{const input=[...container.querySelectorAll('label')].find(e=>e.textContent?.startsWith(label))!.querySelector('input')!;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}))})}
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});container=document.createElement('div');document.body.append(container);root=createRoot(container);fetchMock=vi.fn(async(path:string)=>({ok:true,json:async()=>path==='/api/lead-config'?{enabled:true,deliveryEnabled:false}:path==='/api/account'?{user}:path==='/api/cases'?{revision:1,archive:{activeId:home.id,cases:[home]}}:{saved:true,id:'receipt',emailStatus:'disabled'}}));vi.stubGlobal('fetch',fetchMock)});
afterEach(()=>{act(()=>root.unmount());container.remove();vi.unstubAllGlobals()});
it('offers prominent plan saving with separate unchecked contact and sharing choices',async()=>{await act(async()=>root.render(createElement(PlanCapture,{state:home,user})));expect(container.textContent).toContain('Email me my plan');const boxes=[...container.querySelectorAll<HTMLInputElement>('input[type=checkbox]')];expect(boxes.map(x=>x.checked)).toEqual([false,false]);await fill('First name','Example');await act(async()=>{button('Email me my plan').click()});const save=fetchMock.mock.calls.find(c=>c[0]==='/api/plans');expect(JSON.parse(String((save?.[1] as RequestInit)?.body))).toMatchObject({contactConsent:false,shareConsent:false,emailConsent:true,caseId:home.id});expect(container.textContent).toContain('No summary email was sent')});
it('supports saving without email and keeps failures and form choices visible',async()=>{await act(async()=>root.render(createElement(PlanCapture,{state:home,user})));await fill('First name','Example');fetchMock.mockImplementation(async(path:string)=>{if(path==='/api/plans')throw Error('Example save failure');return {ok:true,json:async()=>path==='/api/account'?{user}:{revision:1,archive:{activeId:home.id,cases:[home]}}}});await act(async()=>button('Save my results without email').click());expect(container.textContent).toContain('Example save failure');expect(container.textContent).toContain('original draft is still here');const save=fetchMock.mock.calls.find(c=>c[0]==='/api/plans');expect(JSON.parse(String((save?.[1] as RequestInit)?.body)).emailConsent).toBe(false)});
it('shows service and request details before asking a guest to verify, and never saves an unverified request',async()=>{await act(async()=>root.render(createElement(ProfessionalHelp,{user:null,onBack:vi.fn(),onRequests:vi.fn()})));expect(container.textContent).not.toContain('Sign in to request help');await act(async()=>button('Occupational therapist assessment').click());await act(async()=>button('Continue').click());expect(container.textContent).toContain('Your details');expect(container.textContent).toContain('ZIP code');expect(container.textContent).toContain('Verify email to send');expect(container.textContent).not.toContain('Send me a code');await act(async()=>button('Verify email to send').click());expect(fetchMock.mock.calls.some(c=>c[0]==='/api/requests')).toBe(false)});
