import {healthNextSteps} from "./health-profile";
import type {HomeProfile} from "./home-profile";
import type {FamilyReport} from "./family-report";
import type {ServiceType} from "./services";
export interface HomeAction {id:string;label:string;title:string;why:string;step:string;service?:ServiceType}
const simple:Record<string,string>={l2:"Ask someone to help clear the usual walking route. Start with small items; leave heavy furniture to someone who can move it safely.",l4:"Arrange for cords to be routed away from the usual walking path.",l6:"Choose a reachable place for a charged phone and agree who to call.",k2:"Ask someone to bring frequently used items within comfortable reach.",k3:"Clear an accessible place to set items beside the preparation area.",k7:"Ask someone to move frequently used items down so climbing is not needed."};
export function homeActions(report:FamilyReport,p?:HomeProfile):HomeAction[]{
 const result:HomeAction[]=healthNextSteps(p).map((step,index)=>({id:`daily-health-${index}`,label:"Daily-life support",title:"A point to discuss",why:"Based on your optional reported mobility or eating answers, not a clinical rating.",step})),known=report.priority.filter(e=>!e.uncertain),diy=known.find(e=>simple[e.code]);
 if(diy)result.push({id:"simple",label:"A simple first step",title:"Start with an everyday adjustment",why:`You reported a concern in ${diy.spaceLabel}: ${diy.question}`,step:simple[diy.code]!});
 const modification=known.find(e=>["e1","e4","e5","b1","b2","b3","b5","b8","br1","br5","s1","s2","ex4","ex6"].includes(e.code));
 if(modification)result.push({id:"modification",label:"Home modifications",title:"Plan the right support for this space",why:`You reported a concern in ${modification.spaceLabel}: ${modification.question}`,step:(modification.guidance?.helps??"Ask a professional to review this space.")+" Confirm fit, installation, cost and permissions before buying or fitting equipment.",service:"home_modifications"});
 const helpGap=p?.helpReach==="no"||p?.helpReach==="unsure";
 if(helpGap)result.push({id:"help",label:"Make a support plan",title:"Agree how help would be reached",why:p?.helpReach==="unsure"?"You were unsure how help would be reached.":"You reported a gap in reaching help.",step:"Discuss a way to call for help from the spaces used most, who would respond and a backup if that person is unavailable.",service:"care_navigation"});
 const techWanted=p?.technology==="interested"||p?.technology==="help";
 if(techWanted)result.push({id:"technology",label:"An option to explore",title:helpGap?"Compare ways to call for help":"Choose one problem for technology to solve",why:"You asked to explore technology. This is a preference, not a finding that equipment is needed.",step:(helpGap?"Ask about a reachable call button or alert system and who receives the alert. ":"Bring one specific difficulty from your results to a technology discussion—for example, reaching lights or contacting support. ")+"Compare setup, ongoing costs, privacy, connectivity and who will maintain it. Ask what happens if it stops working.",service:"technology_support"});
 if(report.unsureCount && !modification)result.push({id:"clarify",label:"Clarify before buying",title:"Get a second pair of eyes",why:`${report.unsureCount} answer${report.unsureCount===1?" was":"s were"} marked not sure.`,step:"Use the room details to choose what you want checked. A professional can help distinguish a change worth making from something that needs no purchase.",service:"professional_assessment"});
 if(p?.routines.includes("night"))result.push({id:"routine-night",label:"Routine",title:"Plan the nighttime route",why:"You reported getting up during the night.",step:"Before bedtime, arrange a clear route, reachable lighting and a way to contact help. Ask an OT to review the route if movement feels difficult."});
 const lighting=known.find(e=>["e2","l3","s4","br3","b6","ex2"].includes(e.code));
 if(lighting && !techWanted && p?.technology!=="no")result.push({id:"lighting-tech",label:"Technology option",title:"Explore easier-to-reach lighting",why:`A lighting concern was reported in ${lighting.spaceLabel}.`,step:"Discuss reachable light controls or motion-activated lighting. Check placement, power, backup arrangements and setup support before choosing a product.",service:"technology_support"});
 return result;
}
export function homeActionsText(report:FamilyReport,p?:HomeProfile){const actions=homeActions(report,p);return actions.length?["PRACTICAL NEXT STEPS",...actions.flatMap(a=>[a.title,a.why,a.step,""])].join("\n"):""}
