import {healthNextSteps} from "./health-profile";
import type {HomeProfile} from "./home-profile";
import type {FamilyReport} from "./family-report";
import type {ServiceType} from "./services";
import {selectedTasks,taskPlace,TASK_LABELS,contextGaps,activeContextAnswers} from "./dynamic-context";
export interface HomeAction {needCode:string;category:"home_modification"|"technology"|"daily_life"|"support_plan"|"routine";id:string;label:string;title:string;why:string;step:string;service?:ServiceType}
const simple:Record<string,string>={l2:"Ask someone to help clear the usual walking route. Start with small items; leave heavy furniture to someone who can move it safely.",l4:"Arrange for cords to be routed away from the usual walking path.",l6:"Choose a reachable place for a charged phone and agree who to call.",k2:"Ask someone to bring frequently used items within comfortable reach.",k3:"Clear an accessible place to set items beside the preparation area.",k7:"Ask someone to move frequently used items down so climbing is not needed."};
type ActionDraft=Omit<HomeAction,"needCode"|"category">;
export function homeActions(report:FamilyReport,p?:HomeProfile):HomeAction[]{
 const result:ActionDraft[]=healthNextSteps(p).map((step,index)=>({id:`daily-health-${index}`,label:"Daily-life support",title:"A point to discuss",why:"Based on your optional reported mobility or eating answers, not a clinical rating.",step})),known=report.priority.filter(e=>!e.uncertain),diy=known.find(e=>simple[e.code]);
 if(p?.dynamic){const d=p.dynamic,a=activeContextAnswers(p);
  for(const task of selectedTasks(p)){const status=a[`task:${task}`];if(!status||status==="prefer_not")continue;const place=taskPlace(p,task);
   result.push({id:`activity-${task}`,label:"Daily activity",title:`Make ${TASK_LABELS[task].toLowerCase()} easier`,why:`You selected this activity${place?` in ${place.label}`:""}${status==="unsure"?" and were unsure about the help needed":" as needing support or a change"}.`,step:task==="eating"&&["chewing","swallowing"].includes(String(a["part:eating"]))?"Discuss difficulty chewing or swallowing with a healthcare professional. This check does not prescribe a diet or food texture. If someone is choking or cannot breathe, call emergency services.":`Discuss the specific difficulty${a[`support:${task}`]==="gap"?" and the gap in available help":""}, current arrangements and what you want to do again. ${["transport","shopping","appointments"].includes(task)?"Check practical support options, actual availability and cost.":"Ask an OT to review the activity and the fit of any equipment or home changes before choosing a modification."}`,service:["transport","shopping","appointments"].includes(task)?"care_navigation":"professional_assessment"});
  }
  const from=d.places.find(s=>s.id===d.layout.sleepId),to=d.places.find(s=>s.id===(d.layout.nightToiletId||d.layout.toiletId));
  if(["yes","varies"].includes(String(a.night)))result.push({id:"dynamic-night",label:"Everyday route",title:"Plan the nighttime journey",why:`You reported nighttime toilet trips${from&&to?` from ${from.label} to ${to.label}`:""}${from?.level&&to?.level&&from.level!==to.level?" between different levels":""}.`,step:"Review the whole route, reachable lighting and how help would be reached. Discuss movement difficulties or level changes with an OT; do not attempt a difficult journey to test it.",service:a.nightDifficulty!=="managed"?"professional_assessment":undefined});
  if(a.social==="more"||a.participation==="less")result.push({id:"participation",label:"Connection and participation",title:"Support the activities and contact you want",why:a.social==="more"?"You said you would like more contact with other people.":"You reported doing less outside the home than you would like.",step:"Discuss the barrier you selected, the activity you want to resume, and practical support such as transport or communication assistance. Confirm local options and availability; no diagnosis is inferred.",service:"care_navigation"});
  if(contextGaps(p).length)result.push({id:"context-gaps",label:"Clarify the picture",title:"Keep the unknown details visible",why:`${contextGaps(p).length} context details are unknown, undisclosed or need clarification.`,step:"Review the home and everyday-life details when you can. Ask a professional to clarify relevant gaps if you want help; missing answers do not establish safety."});
 }
 if(diy)result.push({id:"simple",label:"A simple first step",title:"Start with an everyday adjustment",why:`You reported a concern in ${diy.spaceLabel}: ${diy.question}`,step:simple[diy.code]!});
 const modification=known.find(e=>["e1","e4","e5","b1","b2","b3","b5","b8","br1","br5","s1","s2","ex4","ex6"].includes(e.code));
 if(modification)result.push({id:`modification-${modification.code}`,label:"Home modifications",title:"Plan the right support for this space",why:`You reported a concern in ${modification.spaceLabel}: ${modification.question}`,step:(modification.guidance?.helps??"Ask a professional to review this space.")+" Confirm fit, installation, cost and permissions before buying or fitting equipment.",service:"home_modifications"});
 const helpGap=p?.helpReach==="no"||p?.helpReach==="unsure";
 if(helpGap)result.push({id:"help",label:"Make a support plan",title:"Agree how help would be reached",why:p?.helpReach==="unsure"?"You were unsure how help would be reached.":"You reported a gap in reaching help.",step:"Discuss a way to call for help from the spaces used most, who would respond and a backup if that person is unavailable.",service:"care_navigation"});
 const techWanted=p?.technology==="interested"||p?.technology==="help";
 if(techWanted)result.push({id:"technology",label:"An option to explore",title:helpGap?"Compare ways to call for help":"Choose one problem for technology to solve",why:"You asked to explore technology. This is a preference, not a finding that equipment is needed.",step:(helpGap?"Ask about a reachable call button or alert system and who receives the alert. ":"Bring one specific difficulty from your results to a technology discussion, for example, reaching lights or contacting support. ")+"Compare setup, ongoing costs, privacy, connectivity and who will maintain it. Ask what happens if it stops working.",service:"technology_support"});
 if(report.unsureCount && !modification)result.push({id:"clarify",label:"Clarify before buying",title:"Get a second pair of eyes",why:`${report.unsureCount} answer${report.unsureCount===1?" was":"s were"} marked not sure.`,step:"Use the room details to choose what you want checked. A professional can help distinguish a change worth making from something that needs no purchase.",service:"professional_assessment"});
 if(!p?.dynamic&&p?.routines.includes("night"))result.push({id:"routine-night",label:"Routine",title:"Plan the nighttime route",why:"You reported getting up during the night.",step:"Before bedtime, arrange a clear route, reachable lighting and a way to contact help. Ask an OT to review the route if movement feels difficult."});
 const lighting=known.find(e=>["e2","l3","s4","br3","b6","ex2"].includes(e.code));
 if(lighting && !techWanted && p?.technology!=="no")result.push({id:`lighting-tech-${lighting.code}`,label:"Technology option",title:"Explore easier-to-reach lighting",why:`A lighting concern was reported in ${lighting.spaceLabel}.`,step:"Discuss reachable light controls or motion-activated lighting. Check placement, power, backup arrangements and setup support before choosing a product.",service:"technology_support"});
 const modificationCodes:Record<string,string>={b1:'grab_bar_toilet',b2:'grab_bar_shower',b3:'shower_non_slip_surface',b5:'toilet_transfer_review',b8:'bathroom_non_slip_floor',e1:'entry_access',e4:'entry_steps_ramp_surface',e5:'entry_handrails',br1:'bed_transfer_support',br5:'bed_mobility_review',s1:'stair_handrails',s2:'stair_surface',ex4:'outdoor_handrails',ex6:'outdoor_access'};
 const lightingCodes:Record<string,string>={e2:'motion_lighting_entry',l3:'motion_lighting_living',s4:'motion_lighting_stairs',br3:'motion_lighting_bedroom',b6:'motion_lighting_bathroom',ex2:'motion_lighting_outdoors'};
 return result.map(a=>({...a,category:a.id.startsWith('modification-')?'home_modification':a.id.startsWith('lighting-tech-')||a.id==='technology'?'technology':a.id==='help'?'support_plan':a.id.startsWith('daily-health-')||a.id.startsWith('activity-')?'daily_life':'routine',needCode:a.id.startsWith('modification-')?(modificationCodes[a.id.slice(13)]||'home_access_review'):a.id.startsWith('lighting-tech-')?(lightingCodes[a.id.slice(14)]||'reachable_lighting'):a.id==='technology'?(helpGap?'call_for_help_technology':'technology_setup_review'):a.id.startsWith('daily-health-')?healthCode(a.step):a.id.replaceAll('-','_')}));
}
function healthCode(step:string){return step.startsWith("Discuss usual movement")?"mobility_professional_review":step.startsWith("Discuss help with groceries")?"meal_access_support":step.startsWith("Contact a healthcare professional")?"appetite_swallowing_review":"hydration_support_review"}
export function homeActionsText(report:FamilyReport,p?:HomeProfile){const actions=homeActions(report,p);return actions.length?["PRACTICAL NEXT STEPS",...actions.flatMap(a=>[a.title,a.why,a.step,""])].join("\n"):""}
