import type {FamilyReport} from "./family-report";
import type {HomeProfile} from "./home-profile";
export const REVIEW_LEVELS=["No concerns reported","Clarify unknowns","Review reported concerns","Prioritize professional review"] as const;
export function homeReportSummary(report:FamilyReport,profile?:HomeProfile){
 const percent=(n:number,d:number)=>d?Math.round(n/d*100):null;
 const mobility=!!profile?.fallConcern && !["none","prefer_not"].includes(profile.fallConcern) || !!profile?.movement && ["difficult","help"].includes(profile.movement);
 const significant=report.priority.some(e=>!e.uncertain && e.guidance?.weight===3);
 const level=mobility||significant?3:report.flaggedCount?2:report.unsureCount?1:0;
 return {level:report.answeredCount||mobility?level:null,label:report.answeredCount||mobility?REVIEW_LEVELS[level]:"More answers needed",completion:percent(report.answeredCount,report.totalCount),concerns:percent(report.flaggedCount,report.answeredCount),unknowns:percent(report.unsureCount,report.answeredCount),roomsComplete:percent(report.rooms.filter(r=>r.unansweredCount===0).length,report.rooms.length),reason:mobility?"Your reported movement, falls or balance concerns are a reason to arrange a professional review.":significant?"An answer flags support, movement or another priority concern worth reviewing with a professional.":report.flaggedCount?"Your answers identify everyday issues to review and plan around.":report.unsureCount?"A second pair of eyes can help check the things you were unsure about.":"Other hazards and personal needs can remain outside this short check, even when no concerns are reported."};
}
export function homeSummaryText(report:FamilyReport,profile?:HomeProfile){const s=homeReportSummary(report,profile);const show=(n:number|null)=>n===null?"Not available":`${n}%`;return ["YOUR RESULTS AT A GLANCE",`Completion: ${show(s.completion)} of questions in this report`,`Concerns: ${show(s.concerns)} of answered questions`,`Not sure: ${show(s.unknowns)} of answered questions`,`Rooms completed: ${show(s.roomsComplete)}`,`Reported-concern scale: ${s.label}`,s.reason,"This descriptive scale is not a validated clinical risk score or a probability of falling. A self-check cannot confirm that you are safe.","Request an OT assessment for movement, transfers, falls or equipment fit. Request a MyIntel aging-in-place follow-up for practical modifications, routines and technology. Availability and appointment times must be confirmed."].join("\n")}
