export function AssessmentSources({compact=false}:{compact?:boolean}){
 const content=<>
  <p>MyIntel writes and selects the short home-check questions. We consulted the CDC resources below to check general home-safety themes such as lighting, clear walking routes, bathroom support and stairs. This is not the CDC checklist or a validated CDC assessment.</p>
  <article className="assessment-source-card"><span className="assessment-source-label">PUBLIC HEALTH REFERENCE</span><h3>Centers for Disease Control and Prevention (CDC)</h3><ul><li><a href="https://www.cdc.gov/steadi/pdf/patient/customizable/checkforsafety-brochure-final-customizable-508.pdf" target="_blank" rel="noopener noreferrer">Check for Safety: A Home Fall Prevention Checklist for Older Adults ↗</a><p>The original CDC checklist covers common hazards around the home.</p></li><li><a href="https://www.cdc.gov/steadi/patient-resources/index.html" target="_blank" rel="noopener noreferrer">STEADI patient and caregiver resources ↗</a><p>CDC information about falls prevention and conversations with healthcare professionals.</p></li></ul><p>These original resources are available free on the CDC website. Links open in a new tab.</p></article>
  <h3>How MyIntel creates your report</h3><p>Your answers determine completion percentages, reported concerns and uncertainty. MyIntel’s own rules organize the review-priority scale and practical next steps. They are not a CDC score, a diagnosis or proof that you are safe.</p><p>Mobility and eating questions provide optional daily-life context. They are MyIntel questions, not a validated medical or nutrition screening tool. An OT report is a separate professional assessment; this self-check does not replace it.</p>
  <p className="assessment-source-disclaimer">CDC, HHS and the U.S. government do not endorse MyIntel, its products or services. No CDC approval, partnership or clinical validation is claimed. MyIntel’s shortened check and report wording have not yet completed OT content review.</p>
 </>;
 return compact?<details className="assessment-sources assessment-sources--compact"><summary>Sources &amp; how this check works</summary>{content}</details>:<section className="assessment-sources" aria-labelledby="assessment-sources-heading"><p className="eyebrow">CLEAR SOURCES, CLEAR LIMITS</p><h1 id="assessment-sources-heading">Sources &amp; how this check works</h1>{content}</section>;
}
