"use client";
import {createUuid} from "@/lib/ids";
import {useEffect,useState} from "react";
type Photo={id:string;room:string;kind:string};
type Review={summary:string;rooms:string[];savedAt:string};
async function preparePhoto(file:File):Promise<Blob>{
 if(!["image/jpeg","image/png","image/webp"].includes(file.type) || file.size>10_000_000)throw Error("Choose a JPG, PNG or WebP photo under 10 MB. Convert HEIC photos to JPG first.");
 const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>40_000_000)throw Error("Choose a smaller photo (under 40 megapixels).");const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext("2d");if(!ctx)throw Error("Photo preparation is unavailable in this browser.");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error("Could not prepare this photo.")),"image/jpeg",.85))}finally{bitmap.close()}
}
export function HomeReviewPhotos({requestId,readOnly=false,basePath,audience="myintel"}:{requestId:string;readOnly?:boolean;basePath?:string;audience?:"myintel"|"professional"}){
 const [review,setReview]=useState<Review|null>(null),[photos,setPhotos]=useState<Photo[]>([]),[room,setRoom]=useState(""),[kind,setKind]=useState("wide"),[pending,setPending]=useState<{blob:Blob;url:string;id:string}|null>(null),[consent,setConsent]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
 const base=basePath??`/api/requests/${requestId}/home-review`;
 const load=async()=>{try{const r=await fetch(base,{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error);setReview(d.review);setPhotos(d.photos);setRoom(current=>current||d.review?.rooms[0]||"")}catch(e){setError(e instanceof Error?e.message:"Could not load shared photos.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[requestId]);
 useEffect(()=>()=>{if(pending)URL.revokeObjectURL(pending.url)},[pending]);
 async function choose(file:File|undefined){if(!file)return;setBusy(true);setError("");setNotice("");try{const blob=await preparePhoto(file);setPending({blob,url:URL.createObjectURL(blob),id:createUuid()});setConsent(false)}catch(e){setError(e instanceof Error?e.message:"Choose another photo.")}finally{setBusy(false)}}
 async function upload(){if(!pending||!consent)return;setBusy(true);setError("");try{const r=await fetch(base+"/photos/"+pending.id,{method:"PUT",headers:{"Content-Type":"image/jpeg","X-Photo-Room":encodeURIComponent(room),"X-Photo-Kind":kind,"X-Photo-Consent":"yes"},body:pending.blob});const d=await r.json();if(!r.ok)throw Error(d.error);setPending(null);setNotice("Photo saved with your request. MyIntel can now review it.");await load()}catch(e){setError(e instanceof Error?e.message:"Upload did not finish. Try again.")}finally{setBusy(false)}}
 async function remove(id:string){setBusy(true);setError("");try{const r=await fetch(base+"/photos/"+id,{method:"DELETE"});if(!r.ok)throw Error("Could not remove the photo. Please try again.");await load();setNotice("Photo removed from this request.")}catch(e){setError(e instanceof Error?e.message:"Please try again.")}finally{setBusy(false)}}
 if(loading)return <p role="status">Checking for a shared home check…</p>;
 if(!review && !error)return null;
 return <section className="home-photo-review"><h3>Home check for professional review</h3>{error && <p role="alert" className="app-alert">{error}<button type="button" onClick={()=>{setError("");void load()}}>Refresh</button></p>}{notice && <p role="status">{notice}</p>}{review && <>
 <details><summary>Read the shared home check</summary><pre>{review.summary}</pre><p>Snapshot shared {new Date(review.savedAt).toLocaleDateString()}. Later assessment edits do not change this copy.</p></details>
 <div className="photo-guidance"><div><p className="family-v2__eyebrow">Optional photos · {photos.length} of 6</p><h4>A little context can help.</h4><ol><li><strong>Start wide.</strong> From a comfortable position, show the room and its usual walking route.</li><li><strong>Add one detail.</strong> Show the feature you want to discuss, such as a step or doorway.</li><li><strong>Review before sharing.</strong> Keep people, addresses, medication labels and private documents out of frame. Never climb or test a hazard for a photo.</li></ol><p>Photos support a conversation. They cannot replace an in-person assessment. {audience==="professional"?"The customer specifically shared the photos shown here for this request.":"MyIntel coordinates the review; no professional has automatically received these images."}</p></div></div>
 <div className="home-photo-grid">{photos.map(photo=><figure key={photo.id}><a href={base+"/photos/"+photo.id} target="_blank" rel="noopener noreferrer"><img src={base+"/photos/"+photo.id} alt={`${photo.room}, ${photo.kind==="wide"?"room view":"detail view"}`} loading="lazy"/></a><figcaption>{photo.room} · {photo.kind==="wide"?"Room view":"Detail"}</figcaption>{!readOnly && <button type="button" disabled={busy} onClick={()=>remove(photo.id)}>Remove photo</button>}</figure>)}</div>
 {!readOnly && photos.length<6 && <><div className="home-fields"><label>Room<select value={room} onChange={e=>setRoom(e.target.value)}>{review.rooms.map((r,i)=><option key={i} value={r}>{r}</option>)}</select></label><label>Photo type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="wide">Room and walking route</option><option value="detail">A feature to discuss</option></select></label></div><label className="photo-picker">Choose a photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{void choose(e.target.files?.[0]);e.target.value=""}}/></label><p>JPG, PNG or WebP, up to 10 MB. A smaller JPEG copy is prepared before upload, without the original file metadata.</p>{pending && <div className="photo-pending"><img src={pending.url} alt="Your selected photo, not uploaded yet"/><p>Not uploaded yet. Check this image before sharing.</p><label className="home-outside"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I have permission to share this photo with MyIntel for this professional-help request.</label><button type="button" className="app-primary" disabled={busy||!consent||!room} onClick={upload}>{busy?"Saving photo…":"Share this photo with MyIntel"}</button><button type="button" className="app-secondary" disabled={busy} onClick={()=>setPending(null)}>Discard selection</button></div>}</>}
 </>}</section>;
}
