import type {CaseApi} from "@/lib/case-store";
import type {FamilyReport} from "@/domain/family-report";
import {profileLines} from "@/domain/home-profile";
export function HomeInsights({api,report,onRooms}:{api:CaseApi;report:FamilyReport;onRooms:()=>void}){
 const total=report.totalCount,unanswered=total-report.answeredCount,clear=report.answeredCount-report.flaggedCount-report.unsureCount;
 const segments=[{label:"Concern reported",value:report.flaggedCount,tone:"concern"},{label:"Not sure",value:report.unsureCount,tone:"unsure"},{label:"No concern reported",value:clear,tone:"clear"},{label:"Unanswered",value:unanswered,tone:"unanswered"}];
 const lines=profileLines(api.state.homeProfile);
 return <><section className="home-insights" aria-labelledby="coverage-heading"><div className="home-coverage-heading"><div><h2 id="coverage-heading">How much have you checked?</h2><p>Completion covers your selected rooms, not the whole home’s safety.</p></div><strong>{total?Math.round(report.answeredCount/total*100):0}%<small>answered</small></strong></div><div className="home-answer-bar" aria-hidden="true">{segments.map(s=><span key={s.tone} className={s.tone} style={{width:(total?s.value/total*100:0)+"%"}}/>)}</div><ul className="home-answer-key">{segments.map(s=><li key={s.tone}><i className={s.tone} aria-hidden="true"/><span>{s.label}</span><strong>{s.value}</strong></li>)}</ul><p>{report.rooms.filter(r=>r.unansweredCount===0).length} of {report.rooms.length} rooms have all questions answered. “Not sure” still needs a closer look.</p>{unanswered>0 && <button className="family-v2__back" onClick={onRooms}>Return to unanswered questions →</button>}</section>
 {lines.length>0 && <section className="home-context"><h2>The home and daily life</h2><ul>{lines.map(line=><li key={line}>{line}</li>)}</ul>{api.state.homeProfile?.routines.includes("night") && <p><strong>A useful starting point:</strong> review the route between the bedroom and bathroom, alongside any concerns listed below.</p>}{api.state.homeProfile?.livingWith==="alone" && <p><strong>For professional review:</strong> discuss how help could be reached when nobody else is home.</p>}<p className="family-v2__fine-print">Reported context. This does not change the question ratings or establish a clinical risk level.</p></section>}</>;
}
