"use client";
import {useEffect,useRef} from "react";
import type {CaseApi} from "@/lib/case-store";
import {EMPTY_PROFILE,HOME_TYPES,ROUTINES,GOALS,suggestedRooms,USED_AREAS,HELP_STYLE} from "@/domain/home-profile";
export function HomeSetup({api,step}:{api:CaseApi;step:"routine"|"home"}){
  const p=api.state.homeProfile??EMPTY_PROFILE,heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{heading.current?.focus()},[step]);
  const used=p.usedAreas??[];
  const chooseArea=(area:keyof typeof USED_AREAS)=>api.patchHomeProfile({usedAreas:used.includes(area)?used.filter(a=>a!==area):[...used,area]});
  const go=(phase:"routine"|"home"|"rooms")=>api.setFamilyPosition({phase,roomIndex:0,questionIndex:0});
  return <main className="family-v2 home-setup"><div className="home-stage" aria-label="Home check stages"><span className={step==="routine"?"current":"done"}>1 · Daily life</span><span className={step==="home"?"current":""}>2 · Your home</span><span>3 · Room check</span><span>4 · Next steps</span></div><section className="family-v2__card">
    <figure className="home-editorial-photo"><img src="/home-interior.webp" alt="A lived-in room with everyday seating and natural light" width={1000} height={863}/><figcaption>Your everyday spaces, at your pace.</figcaption></figure>
    <p className="family-v2__eyebrow">{step==="routine"?"Start with the person":"Prepare your room checklist"}</p>
    <h1 ref={heading} tabIndex={-1}>{step==="routine"?"What does daily life look like?":"Let’s follow a normal day."}</h1>
    <p className="family-v2__lead">{step==="routine"?"A home check should fit the way you live. These questions are optional; share only what you’re comfortable with.":"Think about where the person sleeps, washes, eats and spends time. Leave spare rooms out. Include a route they avoid because it feels difficult if you want help with it."}</p>
    {step==="routine"?<>
      <div className="home-fields"><label>Who is this check for?<select value={p.forWhom} onChange={e=>api.patchHomeProfile({forWhom:e.target.value as typeof p.forWhom})}><option value="">Choose, or leave blank</option><option value="self">Myself</option><option value="family">A family member</option><option value="support">Someone I support</option></select></label><label>Who lives in the home?<select value={p.livingWith} onChange={e=>api.patchHomeProfile({livingWith:e.target.value as typeof p.livingWith})}><option value="">Choose, or leave blank</option><option value="alone">The person lives alone</option><option value="others">The person lives with others</option><option value="varies">It varies</option><option value="prefer_not">Prefer not to say</option></select></label><label>What helps with getting around?<select value={p.mobility} onChange={e=>api.patchHomeProfile({mobility:e.target.value as typeof p.mobility})}><option value="">Choose, or leave blank</option><option value="none">No walking aid</option><option value="cane">Cane</option><option value="walker">Walker</option><option value="wheelchair">Wheelchair</option><option value="varies">It varies / another aid</option><option value="prefer_not">Prefer not to say</option></select></label><label>What matters most right now?<select value={p.goal} onChange={e=>api.patchHomeProfile({goal:e.target.value as typeof p.goal})}><option value="">Choose, or leave blank</option>{Object.entries(GOALS).map(([v,label])=><option value={v} key={v}>{label}</option>)}</select></label></div>
      <fieldset className="routine-choices"><legend>Which everyday routines should we keep in mind?</legend><p>Select any that matter. This helps us choose a starting room.</p><div>{Object.entries(ROUTINES).map(([v,label])=><button type="button" key={v} aria-pressed={p.routines.includes(v as keyof typeof ROUTINES)} onClick={()=>api.patchHomeProfile({routines:p.routines.includes(v as keyof typeof ROUTINES)?p.routines.filter(r=>r!==v):[...p.routines,v as keyof typeof ROUTINES]})}><span aria-hidden="true">{p.routines.includes(v as keyof typeof ROUTINES)?"✓":"+"}</span>{label}</button>)}</div></fieldset>
      <details className="family-v2__hint"><summary>Help us make the next steps useful (optional)</summary><div className="home-fields"><label>Could help be reached from the usual spaces if needed?<select value={p.helpReach??""} onChange={e=>api.patchHomeProfile({helpReach:e.target.value as typeof p.helpReach})}><option value="">Leave blank</option><option value="yes">Yes, there is a way to call and someone to respond</option><option value="no">No, there is a gap</option><option value="unsure">I'm not sure</option></select></label><label>What kind of help would suit you?<select value={p.helpStyle??""} onChange={e=>api.patchHomeProfile({helpStyle:e.target.value as typeof p.helpStyle})}><option value="">Leave blank</option>{Object.entries(HELP_STYLE).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Would you like to explore home technology?<select value={p.technology??""} onChange={e=>api.patchHomeProfile({technology:e.target.value as typeof p.technology})}><option value="">Leave blank</option><option value="interested">Yes, if it solves a specific problem</option><option value="help">Maybe, with setup and ongoing help</option><option value="no">Not right now</option></select></label></div><p>There is no need to buy anything to use this check. Your preferences help shape the options at the end.</p></details>
      <div className="family-v2__actions"><button className="family-v2__button family-v2__button--primary" onClick={()=>go("home")}>Next: your home →</button><button className="family-v2__skip" onClick={()=>go("home")}>Skip these questions</button></div>
    </>:<form onSubmit={e=>{e.preventDefault();if(used.length)api.prepareHomeRooms()}}>
      <fieldset className="routine-choices"><legend>Which spaces do you want to check?</legend><p>Select the spaces used regularly, or a space you want help using again. Start with one of each; add another only if it needs a separate look.</p><div>{Object.entries(USED_AREAS).map(([area,label])=><button type="button" key={area} aria-pressed={used.includes(area as keyof typeof USED_AREAS)} onClick={()=>chooseArea(area as keyof typeof USED_AREAS)}><span aria-hidden="true">{used.includes(area as keyof typeof USED_AREAS)?"✓":"+"}</span>{p.forWhom==="self"?label:label.replace(" I "," they ")}</button>)}</div></fieldset>
      <details className="family-v2__hint"><summary>Add home type and levels (optional)</summary><div className="home-fields"><label>Type of home<select value={p.homeType} onChange={e=>api.patchHomeProfile({homeType:e.target.value as typeof p.homeType})}><option value="">Leave blank</option>{Object.entries(HOME_TYPES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Levels in the home<select value={p.levels} onChange={e=>api.patchHomeProfile({levels:Number(e.target.value)})}>{[1,2,3,4].map(n=><option key={n} value={n}>{n}</option>)}</select></label></div><p>More levels will not add more rooms or stairs automatically.</p></details>
      <div className="home-plan-preview"><strong>{used.length?used.length+" everyday spaces selected":"Choose at least one space"}</strong><p>We’ll guide you through one space at a time. You can pause or see your next steps before finishing every question.</p>{api.state.spaces.length>0 && <p>Rooms outside this selection will be set aside, with their answers kept. You can bring them back from your checklist.</p>}</div>
      <div className="family-v2__actions"><button type="submit" disabled={!used.length} className="family-v2__button family-v2__button--primary">Prepare my everyday spaces →</button><button type="button" className="family-v2__button family-v2__button--secondary" onClick={()=>go("routine")}>Back</button><button type="button" className="family-v2__skip" onClick={()=>go("rooms")}>Edit my checklist directly</button></div>
    </form>}
  </section></main>;
}
