"use client";
import {funnelOnce} from "@/lib/funnel";
import {useEffect,useRef} from "react";
import type {CaseApi} from "@/lib/case-store";
import {EMPTY_PROFILE,profileLines} from "@/domain/home-profile";
import {contextPrompts,contextAnswer,answerContext,leaveContextUnknown,contextGaps} from "@/domain/dynamic-context";
export function HomeRoutineConversation({api}:{api:CaseApi}){
 const p=api.state.homeProfile??EMPTY_PROFILE,questions=contextPrompts(p),saved=api.state.familyPosition?.contextQuestionId??"forWhom",review=saved==="review";
 const index=Math.max(0,questions.findIndex(q=>q.id===saved)),q=questions[index]!,value=contextAnswer(p,q.id),heading=useRef<HTMLHeadingElement>(null);
 const go=(id:string)=>api.setFamilyPosition({phase:"routine",roomIndex:0,contextQuestionId:id});
 useEffect(()=>{heading.current?.focus({preventScroll:true});window.scrollTo({top:0,behavior:"instant"})},[saved]);
 const next=()=>q.id==="goal"?api.setFamilyPosition({phase:"home",roomIndex:0}):go(questions[index+1]?.id??"review");
 const back=()=>q.id==="personal"?api.setFamilyPosition({phase:"home",roomIndex:0}):go(questions[Math.max(0,index-1)]!.id);
 if(review)return <main className="family-v2 home-conversation"><section className="family-v2__card"><p className="family-v2__eyebrow">Your check</p><h1 ref={heading} tabIndex={-1}>A check built around your everyday life.</h1><p>We will check the selected spaces and ask for relevant detail when a concern or uncertainty comes up. These answers are reported context, not clinical ratings.</p><details><summary>Review the home and everyday-life answers</summary><ul>{profileLines(p).map((s,i)=><li key={i}>{s}</li>)}</ul></details><details><summary>Details still unknown ({contextGaps(p).length})</summary><ul>{contextGaps(p).map(s=><li key={s}>{s}</li>)}</ul></details><div className="family-v2__actions"><button className="family-v2__button family-v2__button--primary" disabled={!p.dynamic?.places.length} onClick={()=>{funnelOnce(api.state.id,"daily_life_finished");api.prepareHomeRooms()}}>Start my space checks</button><button className="family-v2__back" onClick={()=>go("personal")}>Review everyday life</button><button className="family-v2__back" onClick={()=>api.setFamilyPosition({phase:"home",roomIndex:0})}>Edit the home</button></div></section></main>;
 return <main className="family-v2 home-conversation"><section className="family-v2__card" key={q.id}><p className="family-v2__eyebrow">{q.chapter} · Optional</p><h1 ref={heading} tabIndex={-1}>{q.title}</h1><p className="family-v2__lead">{q.why}</p>{q.multiple&&<p>Choose all that apply, or one “none”, “not sure” or private answer.</p>}<div className="home-conversation-options" role="group" aria-label={q.title}>{Object.entries(q.options).map(([v,label])=>{const selected=Array.isArray(value)?value.includes(v):value===v;return <button key={v} type="button" aria-pressed={selected} onClick={()=>{let next:string|string[]=v;if(q.multiple){const exclusive=["none","unsure","prefer_not"];next=exclusive.includes(v)?[v]:[...(Array.isArray(value)?value:[]).filter(x=>!exclusive.includes(x)&&x!==v),...(!selected?[v]:[])];if(!next.length)return;}api.patchHomeProfile(answerContext(p,q.id,next))}}><span aria-hidden="true">{selected?"✓":"○"}</span>{label}</button>})}</div><details className="home-guide"><summary>Why we ask this</summary><p>{q.why}</p></details><div className="family-v2__actions"><button className="family-v2__button family-v2__button--primary" onClick={next}>Continue</button>{index>0&&<button className="family-v2__back" onClick={back}>Back</button>}</div><button className="family-v2__skip" onClick={()=>{api.patchHomeProfile(leaveContextUnknown(p,q.id));next()}}>Leave this unknown and continue</button>{index>1&&<button className="family-v2__skip" onClick={()=>go("review")}>Pause these details and review my check</button>}</section></main>;
}
