import type {CaseApi} from "@/lib/case-store";
import type {FamilyReport} from "@/domain/family-report";
import {profileLines} from "@/domain/home-profile";
import {homeReportSummary,REVIEW_LEVELS} from "@/domain/home-report-summary";
import {contextGaps} from "@/domain/dynamic-context";
export function HomeInsights({api,report,onRooms}:{api:CaseApi;report:FamilyReport;onRooms:()=>void}){
 const total=report.totalCount,unanswered=total-report.answeredCount,clear=report.answeredCount-report.flaggedCount-report.unsureCount;
 const segments=[{label:"Concern reported",value:report.flaggedCount,tone:"concern"},{label:"Not sure",value:report.unsureCount,tone:"unsure"},{label:"No concern reported",value:clear,tone:"clear"},{label:"Unanswered",value:unanswered,tone:"unanswered"}];
 const lines=profileLines(api.state.homeProfile);
 const gaps=contextGaps(api.state.homeProfile);
 const summary=homeReportSummary(report,api.state.homeProfile),show=(n:number|null)=>n===null?"—":`${n}%`;
 return <><section className="home-insights" aria-labelledby="coverage-heading"><h2 id="coverage-heading">Your results at a glance</h2><p>Percentages describe the questions in this report, including earlier saved answers. They are not a measure of how safe you are.</p><dl className="report-metrics">{[{label:"Check completed",value:summary.completion,note:`${report.answeredCount} of ${total} questions`},{label:"Concern reported",value:summary.concerns,note:"of answered questions"},{label:"Not sure",value:summary.unknowns,note:"of answered questions"},{label:"Rooms completed",value:summary.roomsComplete,note:`${report.rooms.filter(r=>!r.unansweredCount).length} of ${report.rooms.length} selected rooms`}].map(m=><div key={m.label}><dt>{m.label}</dt><dd>{show(m.value)}</dd><small>{m.note}</small></div>)}</dl><div className="home-answer-bar" aria-hidden="true">{segments.map(s=><span key={s.tone} className={s.tone} style={{width:(total?s.value/total*100:0)+"%"}}/>)}</div><ul className="home-answer-key">{segments.map(s=><li key={s.tone}><i className={s.tone} aria-hidden="true"/><span>{s.label}</span><strong>{s.value}</strong></li>)}</ul><p>The bar shows all {total} questions in this report. “Not sure” and unanswered questions still need a closer look.</p>{unanswered>0 && <button className="family-v2__back" onClick={onRooms}>Return to unanswered questions →</button>}<section className="report-review-scale" aria-labelledby="review-scale-heading"><h3 id="review-scale-heading">Reported concerns &amp; review priority</h3><ol>{REVIEW_LEVELS.map((label,index)=><li key={label} className={summary.level===index?"current":""} aria-current={summary.level===index?"step":undefined}>{label}</li>)}</ol><strong>{summary.label}</strong><p>{summary.reason}</p><p className="family-v2__fine-print">This scale describes follow-up priority from your answers. It is not a validated clinical risk score, diagnosis or probability of falling.</p></section></section>
 {gaps.length>0&&<section className="home-context"><h2>What still needs clarification</h2><p>These gaps are separate from the room-check percentages. No answer is inferred from missing information.</p><details><summary>{gaps.length} context details not established</summary><ul>{gaps.map(s=><li key={s}>{s}</li>)}</ul></details></section>}
 {lines.length>0 && <section className="home-context"><h2>The home and daily life</h2><ul>{lines.map(line=><li key={line}>{line}</li>)}</ul>{api.state.homeProfile?.routines.includes("night") && <p><strong>A useful starting point:</strong> review the route between the bedroom and bathroom, alongside any concerns listed below.</p>}{api.state.homeProfile?.livingWith==="alone" && <p><strong>For professional review:</strong> discuss how help could be reached when nobody else is home.</p>}<p className="family-v2__fine-print">Reported context. This does not change the question ratings or establish a clinical risk level.</p></section>}</>;
}
