"use client";
import {useEffect,useRef} from "react";
import type {CaseApi} from "@/lib/case-store";
import {EMPTY_PROFILE,HOME_TYPES,ROUTINES,GOALS,suggestedRooms} from "@/domain/home-profile";
export function HomeSetup({api,step}:{api:CaseApi;step:"routine"|"home"}){
  const p=api.state.homeProfile??EMPTY_PROFILE,heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{heading.current?.focus()},[step]);
  const go=(phase:"routine"|"home"|"rooms")=>api.setFamilyPosition({phase,roomIndex:0,questionIndex:0});
  return <main className="family-v2 home-setup"><div className="home-stage" aria-label="Home check stages"><span className={step==="routine"?"current":"done"}>1 · Daily life</span><span className={step==="home"?"current":""}>2 · Your home</span><span>3 · Room check</span><span>4 · Next steps</span></div><section className="family-v2__card">
    <figure className="home-editorial-photo"><img src="/home-interior.webp" alt="A lived-in room with everyday seating and natural light" width={1000} height={863}/><figcaption>Your everyday spaces, at your pace.</figcaption></figure>
    <p className="family-v2__eyebrow">{step==="routine"?"Start with the person":"Prepare your room checklist"}</p>
    <h1 ref={heading} tabIndex={-1}>{step==="routine"?"What does daily life look like?":"Tell us about the home."}</h1>
    <p className="family-v2__lead">{step==="routine"?"A home check should fit the way you live. These questions are optional; share only what you’re comfortable with.":"We’ll prepare the rooms for you. Review the list before you begin, and change anything that doesn’t fit."}</p>
    {step==="routine"?<>
      <div className="home-fields"><label>Who is this check for?<select value={p.forWhom} onChange={e=>api.patchHomeProfile({forWhom:e.target.value as typeof p.forWhom})}><option value="">Choose, or leave blank</option><option value="self">Myself</option><option value="family">A family member</option><option value="support">Someone I support</option></select></label><label>Who lives in the home?<select value={p.livingWith} onChange={e=>api.patchHomeProfile({livingWith:e.target.value as typeof p.livingWith})}><option value="">Choose, or leave blank</option><option value="alone">The person lives alone</option><option value="others">The person lives with others</option><option value="varies">It varies</option><option value="prefer_not">Prefer not to say</option></select></label><label>What helps with getting around?<select value={p.mobility} onChange={e=>api.patchHomeProfile({mobility:e.target.value as typeof p.mobility})}><option value="">Choose, or leave blank</option><option value="none">No walking aid</option><option value="cane">Cane</option><option value="walker">Walker</option><option value="wheelchair">Wheelchair</option><option value="varies">It varies / another aid</option><option value="prefer_not">Prefer not to say</option></select></label><label>What matters most right now?<select value={p.goal} onChange={e=>api.patchHomeProfile({goal:e.target.value as typeof p.goal})}><option value="">Choose, or leave blank</option>{Object.entries(GOALS).map(([v,label])=><option value={v} key={v}>{label}</option>)}</select></label></div>
      <fieldset className="routine-choices"><legend>Which everyday routines should we keep in mind?</legend><p>Select any that matter. This helps us choose a starting room.</p><div>{Object.entries(ROUTINES).map(([v,label])=><button type="button" key={v} aria-pressed={p.routines.includes(v as keyof typeof ROUTINES)} onClick={()=>api.patchHomeProfile({routines:p.routines.includes(v as keyof typeof ROUTINES)?p.routines.filter(r=>r!==v):[...p.routines,v as keyof typeof ROUTINES]})}><span aria-hidden="true">{p.routines.includes(v as keyof typeof ROUTINES)?"✓":"+"}</span>{label}</button>)}</div></fieldset>
      <div className="family-v2__actions"><button className="family-v2__button family-v2__button--primary" onClick={()=>go("home")}>Next: your home →</button><button className="family-v2__skip" onClick={()=>go("home")}>Skip these questions</button></div>
    </>:<form onSubmit={e=>{e.preventDefault();api.prepareHomeRooms()}}>
      <div className="home-fields"><label>Type of home<select required value={p.homeType} onChange={e=>api.patchHomeProfile({homeType:e.target.value as typeof p.homeType})}><option value="">Choose a home type</option>{Object.entries(HOME_TYPES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Levels inside the home<select value={p.levels} onChange={e=>api.patchHomeProfile({levels:Number(e.target.value)})}>{[1,2,3,4].map(n=><option key={n} value={n}>{n} {n===1?"level":"levels"}</option>)}</select></label>
      {([["bedrooms","Bedrooms",8],["fullBaths","Full bathrooms (with a bath or shower)",6],["halfBaths","Half baths (toilet and sink only)",4]] as const).map(([key,label,max])=><label key={key}>{label}<select value={p[key]} onChange={e=>api.patchHomeProfile({[key]:Number(e.target.value)})}>{Array.from({length:max+1},(_,n)=><option key={n} value={n}>{n}</option>)}</select></label>)}
      <label>Are there steps or stairs you use?<select required value={p.stairs} onChange={e=>api.patchHomeProfile({stairs:e.target.value as typeof p.stairs})}><option value="">Choose an answer</option><option value="yes">Yes</option><option value="no">No</option><option value="unsure">Not sure</option></select></label></div>
      <label className="home-outside"><input type="checkbox" checked={p.outside} onChange={e=>api.patchHomeProfile({outside:e.target.checked})}/>Include an outside area, such as a patio or yard</label>
      <div className="home-plan-preview"><strong>Your suggested checklist</strong><span>{p.bedrooms} {p.bedrooms===1?"bedroom":"bedrooms"} · {p.fullBaths} full + {p.halfBaths} half baths · {p.levels} {p.levels===1?"level":"levels"}</span><p>{suggestedRooms(p).length} rooms and areas, including the front door, living room and kitchen. You’ll confirm which level each room is on next.</p>{api.state.spaces.length>0 && <p>Your existing rooms and answers will be kept. Remove any rooms you no longer need from the checklist.</p>}</div>
      <div className="family-v2__actions"><button type="submit" className="family-v2__button family-v2__button--primary">Prepare my rooms →</button><button type="button" className="family-v2__button family-v2__button--secondary" onClick={()=>go("routine")}>Back</button><button type="button" className="family-v2__skip" onClick={()=>go("rooms")}>Choose rooms myself</button></div>
    </form>}
  </section></main>;
}
