"use client";
import {useEffect,useState} from 'react';
type Plan={id:string;name:string;email:string;phone:string;postal_code:string;contact_consent:number;share_consent:number;snapshot:string|null;created_at:string;coordinator_id:string|null;coordinator_name:string|null;closed_at:string|null};
export function LeadOperations(){
 const [mail,setMail]=useState<{id:string;kind:string;status:string;created_at:string}[]>([]);
 const [plans,setPlans]=useState<Plan[]>([]),[counts,setCounts]=useState<{event:string;bucket:string;total:number}[]>([]),[enabled,setEnabled]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const c=await fetch('/api/lead-config').then(r=>r.json());setEnabled(!!c.enabled);if(!c.enabled)return;const p=await fetch('/api/admin/plans'),f=await fetch('/api/admin/funnel');if(!p.ok||!f.ok)throw Error('Could not load saved plans or counts.');const data=await p.json();setPlans(data.plans);setMail(data.mail??[]);setCounts((await f.json()).counts)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{const id=new URLSearchParams(location.search).get('item');if(id)document.getElementById(`lead-${id}`)?.scrollIntoView({block:'center'})},[plans]);
 async function update(id:string,action:string){setBusy(true);setError('');try{const r=await fetch(`/api/admin/plans/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const d=await r.json();if(!r.ok)throw Error(d.error);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function retry(id:string){setBusy(true);setError("");try{const r=await fetch("/api/admin/mail-retry",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});if(!r.ok)throw Error("Retry could not be confirmed.");await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!enabled)return null;
 return <section className="account-card lead-operations"><div className="section-heading"><h2>Saved plans</h2><button className="app-secondary" onClick={load}>Refresh plans and counts</button></div>{error&&<p role="alert">{error}</p>}<p>Contact only people who gave permission. Result details appear only with separate sharing permission.</p>{plans.length?plans.map(p=><article className="account-card" id={`lead-${p.id}`} key={p.id}><p>Plan saved, {new Date(p.created_at).toLocaleDateString()}{p.closed_at?', closed':''}</p><h3>{p.name}</h3><p>{p.email}{p.phone?`, ${p.phone}`:''}. ZIP: {p.postal_code||'Not provided'}. Preferred contact: email.</p><p>{p.contact_consent?'Permission for MyIntel to contact this person: yes.':'No permission to contact. Do not follow up.'} {p.share_consent?'Results shared with MyIntel staff.':'Results are private.'}</p>{p.snapshot&&<details><summary>Shared results snapshot</summary><pre className="lead-snapshot">{p.snapshot}</pre></details>}{!!p.contact_consent&&!p.closed_at&&<><p>{p.coordinator_name?`Coordinator: ${p.coordinator_name}`:'Needs an owner'}</p><div className="inline-actions"><button className="app-secondary" disabled={busy} onClick={()=>update(p.id,'claim')}>Take responsibility</button><button className="app-secondary" disabled={busy} onClick={()=>update(p.id,'release')}>Return to queue</button><button className="app-secondary" disabled={busy} onClick={()=>update(p.id,'close')}>Close follow-up</button></div></>}</article>):<p>No plans saved yet.</p>}<h2>Email status</h2><p>Accepted means the email service accepted the message, not confirmed inbox delivery. Pending notifications can be retried within 23 hours. Older uncertain sends need manual provider review to avoid duplicates. Disabled messages are never replayed automatically.</p>{mail.map(m=><p key={m.id}>{m.kind=== "plan"?"Customer plan":"Staff notification"}: {m.status.replaceAll("_"," ")}. Reference {m.id}. {m.kind==="staff"&&m.status==="pending"&&<button className="app-secondary" disabled={busy} onClick={()=>retry(m.id)}>Retry notification</button>}</p>)}<h2>Last 30 days</h2><p>Anonymous event counts, not unique people. No answers or contact details are collected. Start-to-results timing includes breaks and does not replace supervised timing with real users.</p><table><thead><tr><th>Event</th><th>Time group</th><th>Count</th></tr></thead><tbody>{counts.map(c=><tr key={c.event+c.bucket}><td>{c.event.replaceAll('_',' ')}</td><td>{c.bucket.replaceAll('_',' ')||'All'}</td><td>{c.total}</td></tr>)}</tbody></table></section>;
}
