"use client";
import {useState} from "react";
import type {CaseApi} from "@/lib/case-store";
import {EMPTY_PROFILE,profileLines} from "@/domain/home-profile";
import {answerContext,contextAnswer,contextPrompts,contextGaps} from "@/domain/dynamic-context";
import {visitContextSignature} from "@/domain/visit-review";
import {HomeLayoutFields} from "./HomeLayoutFields";
export function ProfessionalContext({api}:{api:CaseApi}){
 const p=api.state.homeProfile??EMPTY_PROFILE,qs=contextPrompts(p),[id,setId]=useState("personal"),q=qs.find(q=>q.id===id)??qs[0]!,value=contextAnswer(p,q.id);
 return <section className="panel professional-context"><h2>Home, daily activities and visit scope</h2><p>Record what the resident or supporter reports. Keep professional observations in Assessment. Review the layout and gaps before leaving.</p><details><summary>Home layout and everyday places</summary><HomeLayoutFields api={api}/><p>The clinical space list is managed in Assessment. Compare it with these reported places; no room ratings are copied.</p></details><details><summary>Purposeful everyday-life questions</summary><label>Question<select value={q.id} onChange={e=>setId(e.target.value)}>{qs.map(q=><option key={q.id} value={q.id}>{q.chapter}: {q.title}</option>)}</select></label><h3>{q.title}</h3><p>{q.why}</p><div className="home-conversation-options">{Object.entries(q.options).map(([v,label])=>{const selected=Array.isArray(value)?value.includes(v):value===v;return <button className="btn-sm" type="button" key={v} aria-pressed={selected} onClick={()=>{let next:string|string[]=v;if(q.multiple){const ex=["none","unsure","prefer_not"];next=ex.includes(v)?[v]:[...(Array.isArray(value)?value:[]).filter(x=>!ex.includes(x)&&x!==v),...(!selected?[v]:[])];if(!next.length)return;}api.patchHomeProfile(answerContext(p,q.id,next))}}>{selected?"✓ ":""}{label}</button>})}</div><button className="btn-sm" type="button" onClick={()=>setId(qs[qs.findIndex(x=>x.id===q.id)+1]?.id??"personal")}>Next question</button></details><details><summary>Reported context and unknown details</summary><ul>{profileLines(p).map((s,i)=><li key={i}>{s}</li>)}</ul><ul>{contextGaps(p).map(s=><li key={s}>{s}</li>)}</ul></details><p>Review the case context, clinical space list and any limitations. Confirming this review does not turn reported answers into verified observations.</p><button className="btn-sm" type="button" onClick={()=>api.patchVisit({contextReviewed:visitContextSignature(api.state)})}>Record context and scope review</button>{api.state.visit?.contextReviewed===visitContextSignature(api.state)&&<p role="status">Context and scope review recorded for these details. Changes will require another review.</p>}</section>;
}
