"use client";
import {useEffect,useState,type FormEvent} from "react";
import type {ServiceRequest} from "@/domain/services";

type HandoffInfo={providerReady:boolean;providerName:string|null;hasHome:boolean;photoCount:number;handoff:null|{active:boolean;consentAt:string;shareHome:boolean;sharePhotos:boolean;revokedAt:string|null}};
export function ProfessionalHandoff({request}:{request:ServiceRequest}){
 const [info,setInfo]=useState<HandoffInfo|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[shareContact,setShareContact]=useState(false),[shareHome,setShareHome]=useState(false),[sharePhotos,setSharePhotos]=useState(false);
 const base=`/api/requests/${request.id}/professional-handoff`;
 async function load(){setError("");try{const r=await fetch(base,{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error);setInfo(d)}catch(e){setError(e instanceof Error?e.message:"Could not check sharing.")}}
 useEffect(()=>{void load()},[request.id,request.quote_version]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!shareContact)return;setBusy(true);setError("");try{const r=await fetch(base,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({quoteVersion:request.quote_version,shareContact,shareHome,sharePhotos})}),d=await r.json();if(!r.ok)throw Error(d.error);await load()}catch(e){setError(e instanceof Error?e.message:"Sharing did not save.")}finally{setBusy(false)}}
 async function revoke(){setBusy(true);setError("");try{const r=await fetch(base,{method:"DELETE"}),d=await r.json();if(!r.ok)throw Error(d.error);await load()}catch(e){setError(e instanceof Error?e.message:"Sharing did not stop.")}finally{setBusy(false)}}
 if(!info&&!error)return <p role="status">Checking professional sharing…</p>;
 return <section className="account-card"><h3>Share with the named professional</h3>{error&&<p className="app-alert" role="alert">{error}</p>}{info?.handoff?.active?<><p role="status">You shared your contact details{info.handoff.shareHome?", home-check snapshot":""}{info.handoff.sharePhotos?", and selected photos":""} with <strong>{info.providerName}</strong> on {new Date(info.handoff.consentAt).toLocaleDateString()}.</p><p>Later assessment edits and new photos are not added automatically.</p><button type="button" className="app-secondary" disabled={busy} onClick={revoke}>{busy?"Stopping sharing…":"Stop professional access"}</button></>:!info?.providerReady?<p>MyIntel has not opened direct sharing for this proposal. Your information remains with MyIntel while staff coordinate the next step.</p>:!["quoted","accepted","paid"].includes(request.status)?<p>Direct sharing is not active for this request.</p>:<form onSubmit={submit}><p>This is optional and separate from accepting the proposal. You can stop access later.</p><label className="home-outside"><input type="checkbox" checked={shareContact} onChange={e=>setShareContact(e.target.checked)} required/>I agree MyIntel may share my name, contact details, ZIP code, request and proposal with <strong>{info.providerName}</strong> so they can follow up about this request.</label>{info.hasHome&&<label className="home-outside"><input type="checkbox" checked={shareHome} onChange={e=>{setShareHome(e.target.checked);if(!e.target.checked)setSharePhotos(false)}}/>Also share the saved home-check snapshot attached to this request.</label>}{info.photoCount>0&&shareHome&&<label className="home-outside"><input type="checkbox" checked={sharePhotos} onChange={e=>setSharePhotos(e.target.checked)}/>Also share the {info.photoCount} photo{info.photoCount===1?"":"s"} currently attached. New photos will need new consent.</label>}<button className="app-primary" disabled={busy||!shareContact}>{busy?"Saving consent…":"Share with this professional"}</button></form>}</section>;
}
