"use client";
import {useEffect,useState} from "react";
import {SERVICES,REQUEST_STATUS,type ServiceType,type RequestStatus} from "@/domain/services";
import {HomeReviewPhotos} from "./HomeReviewPhotos";

type Referral={id:string;service:ServiceType;name:string;email:string;phone:string;contact_method:string;postal_code:string;status:RequestStatus;scope:string;provider_name:string;consent_at:string;share_home:number;share_photos:number;updated_at:string};
export function ProfessionalReferrals(){
 const [referrals,setReferrals]=useState<Referral[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/professional/referrals",{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error);setReferrals(d.referrals)}catch(e){setError(e instanceof Error?e.message:"Could not open shared requests.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 return <><div className="page-heading"><div><p className="eyebrow">CUSTOMER-CONSENTED HANDOFFS</p><h1>Shared requests</h1><p>Only current requests a customer specifically shared with your linked professional listing appear here.</p></div><button className="app-secondary" disabled={loading} onClick={load}>Refresh</button></div>{error&&<p className="app-alert" role="alert">{error}</p>}{loading?<p role="status">Opening shared requests…</p>:!referrals.length?<div className="empty-work"><h2>No requests are shared with this account.</h2><p>MyIntel staff must link your approved account to a reviewed listing, and the customer must then consent to the named handoff.</p></div>:<div className="request-list">{referrals.map(r=><article className="request-card" key={r.id}><div className="section-heading"><div><span className="case-type">Shared {new Date(r.consent_at).toLocaleDateString()} · Ref {r.id.slice(0,8).toUpperCase()}</span><h2>{r.name} · {SERVICES[r.service].title}</h2></div><span className={"request-status status-"+r.status}>{REQUEST_STATUS[r.status]}</span></div><p><strong>Contact preference:</strong> {r.contact_method==="phone"&&r.phone?`${r.phone} · `:""}{r.email}</p><p><strong>Service area:</strong> ZIP {r.postal_code}</p>{r.scope&&<div className="proposal-scope"><h3>Agreed scope</h3><p>{r.scope}</p></div>}<p className="account-note">Use these details only for this request. Customer access ends if consent, approval, listing assignment or the proposal changes.</p>{!!r.share_home&&<HomeReviewPhotos requestId={r.id} readOnly audience="professional" basePath={`/api/professional/referrals/${r.id}/home-review`}/>}</article>)}</div>}</>;
}
