"use client";
import {useEffect,useState} from "react";
import {SERVICES,REQUEST_STATUS,type AccountUser,type ServiceRequest} from "@/domain/services";
export function RequestCenter({user,paymentsEnabled,onNew}:{user:AccountUser|null;paymentsEnabled:boolean;onNew:()=>void}){
  const [requests,setRequests]=useState<ServiceRequest[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState("");
  const load=()=>{setLoading(true);setError("");fetch("/api/requests",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d}).then(d=>setRequests(d.requests)).catch(e=>setError(e.message||"Could not load requests.")).finally(()=>setLoading(false))};
  useEffect(()=>{if(user)load();else setLoading(false)},[user]);
  async function action(r:ServiceRequest,kind:"accept"|"checkout"){
    setBusy(r.id);setError("");try{const response=await fetch("/api/requests/"+r.id+"/"+kind,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({quoteVersion:r.quote_version})});const data=await response.json();if(!response.ok)throw Error(data.error);if(kind==="checkout"){const url=new URL(data.url);if(url.protocol!=="https:" || url.hostname!=="checkout.stripe.com")throw Error("Checkout could not be opened.");window.location.assign(url.href)}else load()}catch(e){setError(e instanceof Error?e.message:"Please try again.")}finally{setBusy("")}
  }
  return <main className="overview requests-page"><div className="page-heading"><div><p className="eyebrow">HELP, WITH A CLEAR NEXT STEP</p><h1>My requests</h1><p>See what’s been received, review a proposal, and decide when you’re ready.</p></div><button className="app-primary" onClick={onNew}>Request help</button></div>
    {!user?<section className="empty-work"><h2>Sign in to see your requests</h2><p>Your requests are linked to your account.</p><a className="app-primary" href="/signin-with-chatgpt?return_to=%2F%3Fview%3Drequests" target="_top">Continue with ChatGPT</a></section>:<>
      <div className="section-heading"><p>Submitting a request does not confirm a booking or charge your card.</p><button className="app-secondary" disabled={loading} onClick={load}>Refresh status</button></div>
      {error && <p className="app-alert" role="alert">{error}</p>}{loading?<p role="status">Loading your requests…</p>:requests.length===0 && !error?<div className="empty-work"><h2>No requests yet</h2><p>Ask for a professional assessment, home modifications, technology support, or help choosing a next step.</p></div>:<div className="request-list">{requests.map(r=><article className="request-card" key={r.id}><div className="section-heading"><div><span className="case-type">{new Date(r.created_at).toLocaleDateString()} · Ref {r.id.slice(0,8).toUpperCase()}</span><h2>{SERVICES[r.service].title}</h2></div><span className={"request-status status-"+r.status}>{REQUEST_STATUS[r.status]}</span></div><p>{r.status==="submitted"?"Your request is in MyIntel’s queue. Availability and next steps still need to be confirmed.":r.status==="reviewing"?"MyIntel is checking the available options. Your proposal will appear here.":r.status==="paid"?"Payment was confirmed by the payment provider. MyIntel will coordinate the agreed service.":r.status==="completed"?"This service has been marked complete by MyIntel.":r.status==="cancelled"?"This request is closed. You can send a new request whenever you need help.":"Review who will help, what is included, and the price before proceeding."}</p>
      {r.provider_name && <p><strong>Professional:</strong> {r.provider_name}</p>}{r.scope && <div className="proposal-scope"><h3>What’s included</h3><p>{r.scope}</p></div>}{r.amount_cents!==null && <p className="proposal-price">{new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(r.amount_cents/100)} <small>Service price · USD</small></p>}
      {r.status==="quoted" && <button className="app-primary" disabled={busy===r.id} onClick={()=>action(r,"accept")}>{busy===r.id?"Saving…":"Accept this proposal"}</button>}
      {r.status==="accepted" && (paymentsEnabled?<button className="app-primary" disabled={busy===r.id} onClick={()=>action(r,"checkout")}>{busy===r.id?"Opening checkout…":"Continue to secure payment"}</button>:<p className="account-note">Your acceptance is saved. Online payment is not enabled yet; no charge has been made.</p>)}
      <p className="request-contact">Follow-up by {r.contact_method==="phone"?"phone · "+r.phone:"email · "+r.email}</p></article>)}</div>}
    </>}
  </main>;
}
